argo_cd_chart_url = "https://argoproj.github.io/argo-helm"
argo_cd_chart_version = "7.6.4"
kiali_chart_url = "https://kiali.org/helm-charts"
kiali_version = "1.89.3"
kube_prometheus_stack_chart_url = "https://prometheus-community.github.io/helm-charts"
kube_prometheus_stack_version = "62.7.0"
istio_chart_version = "1.23.0"
istio_chart_url = "https://istio-release.storage.googleapis.com/charts"
