argo_cd_chart_url = "https://argoproj.github.io/argo-helm"
argo_cd_chart_version = "8.0.17"
kiali_chart_url = "https://kiali.org/helm-charts"
kiali_version = "2.11.0"
kube_prometheus_stack_chart_url = "https://prometheus-community.github.io/helm-charts"
kube_prometheus_stack_version = "73.2.0"
istio_chart_version = "1.26.0"
istio_chart_url = "https://istio-release.storage.googleapis.com/charts"
